const { src, dest, watch, parallel, series } = require('gulp')
const htmlmin = require('gulp-htmlmin')
const concat = require('gulp-concat')
const cssMin = require('gulp-csso')
const rename = require('gulp-rename')
const autoprefixer = require('gulp-autoprefixer')
const imgcompress = require('compress-images')
const browserSync = require('browser-sync').create()
